export const defaultColors = [
  {
    "Id": "c1",
    "Name": "Black",
    "ColorBrush": null,
    "IsCustom": true,
    "ColorType": 2,
    "Alpha": 255,
    "R": 0,
    "G": 0,
    "B": 0,
    "C": 0,
    "M": 0,
    "Y": 0,
    "K": 0,
    "Tint": 100,
    "Value": "#000000",
    "IsBlack": true,
    "IsWhite": false
  },
  {
    "Id": "c2",
    "Name": "Dark Gray",
    "ColorBrush": null,
    "IsCustom": true,
    "ColorType": 0,
    "Alpha": 255,
    "R": 169,
    "G": 169,
    "B": 169,
    "C": 0,
    "M": 0,
    "Y": 0,
    "K": 0,
    "Tint": 0,
    "Value": "#A9A9A9",
    "IsBlack": false,
    "IsWhite": false
  },
  {
    "Id": "c3",
    "Name": "Gray",
    "ColorBrush": null,
    "IsCustom": true,
    "ColorType": 0,
    "Alpha": 255,
    "R": 128,
    "G": 128,
    "B": 128,
    "C": 0,
    "M": 0,
    "Y": 0,
    "K": 0,
    "Tint": 0,
    "Value": "#808080",
    "IsBlack": false,
    "IsWhite": false
  },
  {
    "Id": "c4",
    "Name": "Light Gray",
    "ColorBrush": null,
    "IsCustom": true,
    "ColorType": 0,
    "Alpha": 255,
    "R": 211,
    "G": 211,
    "B": 211,
    "C": 0,
    "M": 0,
    "Y": 0,
    "K": 0,
    "Tint": 0,
    "Value": "#D3D3D3",
    "IsBlack": false,
    "IsWhite": false
  },
  {
    "Id": "c5",
    "Name": "White",
    "ColorBrush": null,
    "IsCustom": true,
    "ColorType": 2,
    "Alpha": 255,
    "R": 255,
    "G": 255,
    "B": 255,
    "C": 0,
    "M": 0,
    "Y": 0,
    "K": 0,
    "Tint": 0,
    "Value": "#FFFFFF",
    "IsBlack": false,
    "IsWhite": true
  },
  {
    "Id": "c6",
    "Name": "Brown",
    "ColorBrush": null,
    "IsCustom": true,
    "ColorType": 0,
    "Alpha": 255,
    "R": 139,
    "G": 69,
    "B": 19,
    "C": 0,
    "M": 0,
    "Y": 0,
    "K": 0,
    "Tint": 0,
    "Value": "#8B4513",
    "IsBlack": false,
    "IsWhite": false
  },
  {
    "Id": "c7",
    "Name": "Dark Red",
    "ColorBrush": null,
    "IsCustom": true,
    "ColorType": 0,
    "Alpha": 255,
    "R": 139,
    "G": 0,
    "B": 0,
    "C": 0,
    "M": 0,
    "Y": 0,
    "K": 0,
    "Tint": 0,
    "Value": "#8B0000",
    "IsBlack": false,
    "IsWhite": false
  },
  {
    "Id": "c8",
    "Name": "Red",
    "ColorBrush": null,
    "IsCustom": true,
    "ColorType": 0,
    "Alpha": 255,
    "R": 255,
    "G": 0,
    "B": 0,
    "C": 0,
    "M": 0,
    "Y": 0,
    "K": 0,
    "Tint": 0,
    "Value": "#FF0000",
    "IsBlack": false,
    "IsWhite": false
  },
  {
    "Id": "c9",
    "Name": "Pink",
    "ColorBrush": null,
    "IsCustom": true,
    "ColorType": 0,
    "Alpha": 255,
    "R": 255,
    "G": 192,
    "B": 203,
    "C": 0,
    "M": 0,
    "Y": 0,
    "K": 0,
    "Tint": 0,
    "Value": "#FFC0CB",
    "IsBlack": false,
    "IsWhite": false
  },
  {
    "Id": "c10",
    "Name": "Orange",
    "ColorBrush": null,
    "IsCustom": true,
    "ColorType": 0,
    "Alpha": 255,
    "R": 255,
    "G": 165,
    "B": 0,
    "C": 0,
    "M": 0,
    "Y": 0,
    "K": 0,
    "Tint": 0,
    "Value": "#FFA500",
    "IsBlack": false,
    "IsWhite": false
  },
  {
    "Id": "c11",
    "Name": "Gold",
    "ColorBrush": null,
    "IsCustom": true,
    "ColorType": 0,
    "Alpha": 255,
    "R": 255,
    "G": 215,
    "B": 0,
    "C": 0,
    "M": 0,
    "Y": 0,
    "K": 0,
    "Tint": 0,
    "Value": "#FFD700",
    "IsBlack": false,
    "IsWhite": false
  },
  {
    "Id": "c12",
    "Name": "Yellow",
    "ColorBrush": null,
    "IsCustom": true,
    "ColorType": 0,
    "Alpha": 255,
    "R": 255,
    "G": 255,
    "B": 0,
    "C": 0,
    "M": 0,
    "Y": 0,
    "K": 0,
    "Tint": 0,
    "Value": "#FFFF00",
    "IsBlack": false,
    "IsWhite": false
  },
  {
    "Id": "c13",
    "Name": "Light Yellow",
    "ColorBrush": null,
    "IsCustom": true,
    "ColorType": 0,
    "Alpha": 255,
    "R": 255,
    "G": 255,
    "B": 224,
    "C": 0,
    "M": 0,
    "Y": 0,
    "K": 0,
    "Tint": 0,
    "Value": "#FFFFE0",
    "IsBlack": false,
    "IsWhite": false
  },
  {
    "Id": "c14",
    "Name": "Green",
    "ColorBrush": null,
    "IsCustom": true,
    "ColorType": 0,
    "Alpha": 255,
    "R": 0,
    "G": 128,
    "B": 0,
    "C": 0,
    "M": 0,
    "Y": 0,
    "K": 0,
    "Tint": 0,
    "Value": "#008000",
    "IsBlack": false,
    "IsWhite": false
  },
  {
    "Id": "c15",
    "Name": "Light Green",
    "ColorBrush": null,
    "IsCustom": true,
    "ColorType": 0,
    "Alpha": 255,
    "R": 144,
    "G": 238,
    "B": 144,
    "C": 0,
    "M": 0,
    "Y": 0,
    "K": 0,
    "Tint": 0,
    "Value": "#90EE90",
    "IsBlack": false,
    "IsWhite": false
  },
  {
    "Id": "c16",
    "Name": "Dark Cyan",
    "ColorBrush": null,
    "IsCustom": true,
    "ColorType": 0,
    "Alpha": 255,
    "R": 0,
    "G": 139,
    "B": 139,
    "C": 0,
    "M": 0,
    "Y": 0,
    "K": 0,
    "Tint": 0,
    "Value": "#008B8B",
    "IsBlack": false,
    "IsWhite": false
  },
  {
    "Id": "c17",
    "Name": "Cyan",
    "ColorBrush": null,
    "IsCustom": true,
    "ColorType": 0,
    "Alpha": 255,
    "R": 0,
    "G": 255,
    "B": 255,
    "C": 0,
    "M": 0,
    "Y": 0,
    "K": 0,
    "Tint": 0,
    "Value": "#00FFFF",
    "IsBlack": false,
    "IsWhite": false
  },
  {
    "Id": "c18",
    "Name": "Dark Blue",
    "ColorBrush": null,
    "IsCustom": true,
    "ColorType": 0,
    "Alpha": 255,
    "R": 0,
    "G": 0,
    "B": 139,
    "C": 0,
    "M": 0,
    "Y": 0,
    "K": 0,
    "Tint": 0,
    "Value": "#00008B",
    "IsBlack": false,
    "IsWhite": false
  },
  {
    "Id": "c19",
    "Name": "Blue",
    "ColorBrush": null,
    "IsCustom": true,
    "ColorType": 0,
    "Alpha": 255,
    "R": 0,
    "G": 0,
    "B": 255,
    "C": 0,
    "M": 0,
    "Y": 0,
    "K": 0,
    "Tint": 0,
    "Value": "#0000FF",
    "IsBlack": false,
    "IsWhite": false
  },
  {
    "Id": "c20",
    "Name": "Sky Blue",
    "ColorBrush": null,
    "IsCustom": true,
    "ColorType": 0,
    "Alpha": 255,
    "R": 135,
    "G": 206,
    "B": 235,
    "C": 0,
    "M": 0,
    "Y": 0,
    "K": 0,
    "Tint": 0,
    "Value": "#87CEEB",
    "IsBlack": false,
    "IsWhite": false
  },
  {
    "Id": "c21",
    "Name": "Dark Magenta",
    "ColorBrush": null,
    "IsCustom": true,
    "ColorType": 0,
    "Alpha": 255,
    "R": 139,
    "G": 0,
    "B": 139,
    "C": 0,
    "M": 0,
    "Y": 0,
    "K": 0,
    "Tint": 0,
    "Value": "#8B008B",
    "IsBlack": false,
    "IsWhite": false
  },
  {
    "Id": "c22",
    "Name": "Magenta",
    "ColorBrush": null,
    "IsCustom": true,
    "ColorType": 0,
    "Alpha": 255,
    "R": 255,
    "G": 0,
    "B": 255,
    "C": 0,
    "M": 0,
    "Y": 0,
    "K": 0,
    "Tint": 0,
    "Value": "#FF00FF",
    "IsBlack": false,
    "IsWhite": false
  },
  {
    "Id": "c23",
    "Name": "Purple",
    "ColorBrush": null,
    "IsCustom": true,
    "ColorType": 0,
    "Alpha": 255,
    "R": 75,
    "G": 0,
    "B": 130,
    "C": 0,
    "M": 0,
    "Y": 0,
    "K": 0,
    "Tint": 0,
    "Value": "#4B0082",
    "IsBlack": false,
    "IsWhite": false
  },
  {
    "Id": "c24",
    "Name": "Lavender",
    "ColorBrush": null,
    "IsCustom": true,
    "ColorType": 0,
    "Alpha": 255,
    "R": 230,
    "G": 230,
    "B": 250,
    "C": 0,
    "M": 0,
    "Y": 0,
    "K": 0,
    "Tint": 0,
    "Value": "#E6E6FA",
    "IsBlack": false,
    "IsWhite": false
  }
]